# Generated by Django 5.0.2 on 2024-02-17 11:39

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("logo", models.FileField(upload_to="logos/")),
                (
                    "company_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hex_value",
                                message="Hex value must be in the format #XXXXXX",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("website", models.URLField(max_length=255)),
            ],
        ),
    ]
