# Generated by Django 5.0.2 on 2024-02-20 16:38

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("logo", models.FileField(upload_to="logos/")),
                (
                    "company_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_hex_value",
                                message="Hex value must be in the format #XXXXXX",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("website", models.URLField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                ("posted_at", models.DateField()),
                (
                    "contract",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        max_length=255,
                        verbose_name="Contract type",
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Job location"),
                ),
                (
                    "apply",
                    models.URLField(max_length=255, verbose_name="Application URL"),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Job description"
                    ),
                ),
                (
                    "requirements",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Job requirements"
                    ),
                ),
                (
                    "role",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Role details"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.company",
                    ),
                ),
            ],
        ),
    ]
