# Generated by Django 5.0.2 on 2024-02-17 11:39

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.CharField(max_length=255)),
                ("posted_at", models.DateField()),
                (
                    "contract",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        max_length=255,
                    ),
                ),
                (
                    "location",
                    models.CharField(max_length=255, verbose_name="Role location"),
                ),
                (
                    "apply",
                    models.URLField(max_length=255, verbose_name="Application URL"),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Job description"
                    ),
                ),
                (
                    "requirements",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Job requirements"
                    ),
                ),
                (
                    "role",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Role details"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.company",
                    ),
                ),
            ],
        ),
    ]
