# Generated by Django 5.0.2 on 2024-02-20 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.CharField(max_length=1000)),
                (
                    "contact_received",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 2, 20, 8, 2, 6, 747196)
                    ),
                ),
            ],
        ),
    ]
