# Generated by Django 5.0.2 on 2024-02-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_alter_contact_contact_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="replied",
            field=models.BooleanField(default=False),
        ),
    ]
